version: '3.9'

volumes:
  STORE_VOLUME:
  SAMPLE_NODE_MODULES:

services:
  tkrzw:
    build:
      context: ./docker/tkrzw
    init: true
    ports:
      - 1978:1978
    volumes:
      - type: volume
        source: STORE_VOLUME
        target: /var/db
    command:
      - tkrzw_server
      - --async
      - --threads
      - "4"
      - --log_level
      - debug
      - /var/db/casket.tkh#num_buckets=10M

  node:
    build:
      context: ./docker/node
    init: true
    working_dir: /sample
    environment:
      - TKRZW_HOST=dns:///tkrzw:1978
    volumes:
      - type: bind
        source: ./sample
        target: /sample
    profiles:
      - poc
    command:
      - node
      - index.js

